import type { GalleryItem } from "@/lib/gallery-data"

export const designIdeasCategories: { id: string; label: string }[] = [
  { id: "all", label: "All Ideas" },
  { id: "style", label: "By Style" },
  { id: "location", label: "By Location" },
  { id: "featured", label: "Featured" },
]

export const designIdeasItems: GalleryItem[] = [
  // Styles - using room style slugs
  {
    id: "1",
    title: "Nepali Traditional",
    description: "Warm earthy tones with traditional Nepali patterns and handcrafted elements across all room types.",
    category: "style",
    style: "nepali-traditional",
    type: "image",
    src: "/images/luxury-living-room.png",
    span: "large",
  },
  {
    id: "2",
    title: "Himalayan Spa",
    description: "Calming colors inspired by mountain hot springs with natural materials for rejuvenation.",
    category: "style",
    style: "himalayan-spa",
    type: "image",
    src: "/images/luxury-bedroom.png",
    span: "tall",
  },
  {
    id: "3",
    title: "Himalayan Minimalist",
    description: "Clean lines inspired by mountain landscapes with natural materials and serene colors.",
    category: "style",
    style: "himalayan-minimalist",
    type: "image",
    src: "/images/luxury-kitchen.png",
    span: "wide",
  },
  {
    id: "4",
    title: "Newari Heritage",
    description: "Traditional Newari design with intricate carvings and rich cultural motifs.",
    category: "style",
    style: "newari-heritage",
    type: "image",
    src: "/images/luxury-dining-room.png",
    span: "tall",
  },
  {
    id: "5",
    title: "Kathmandu Contemporary",
    description: "Modern design blended with traditional Nepali textiles and vibrant cultural colors.",
    category: "style",
    style: "kathmandu-contemporary",
    type: "image",
    src: "/images/luxury-living-room.png",
    span: "tall",
  },
  // Locations - using room location slugs
  {
    id: "6",
    title: "Kathmandu City",
    description: "Urban sophistication meets traditional charm in Kathmandu interiors. Perfect for city living with a blend of modern amenities and cultural heritage.",
    category: "location",
    location: "kathmandu",
    type: "image",
    src: "/images/luxury-dining-room.png",
    span: "wide",
  },
  {
    id: "7",
    title: "Pokhara Lakeside",
    description: "Lakeside tranquility inspires Pokhara interiors. Natural light, panoramic views, and relaxed elegance define this serene style.",
    category: "location",
    location: "pokhara",
    type: "image",
    src: "/images/luxury-bedroom.png",
    span: "tall",
  },
  {
    id: "8",
    title: "Chitwan Jungle",
    description: "Jungle-inspired elegance for Chitwan interiors. Earthy tones, natural materials, and wildlife motifs create a unique connection to nature.",
    category: "location",
    location: "chitwan",
    type: "image",
    src: "/images/luxury-kitchen.png",
    span: "wide",
  },
  {
    id: "13",
    title: "Lalitpur Residence",
    description: "Traditional Newari craftsmanship meets modern luxury in Lalitpur homes. Features intricate woodwork, traditional patterns, and contemporary amenities.",
    category: "location",
    location: "lalitpur",
    type: "image",
    src: "/images/luxury-living-room.png",
    span: "large",
  },
  // Featured - navigate to style galleries
  {
    id: "9",
    title: "Modern Living Room",
    description: "A stunning modern living room design that combines comfort with contemporary aesthetics, perfect for urban living in Kathmandu.",
    category: "featured",
    style: "kathmandu-contemporary",
    location: "kathmandu",
    type: "image",
    src: "/images/luxury-living-room.png",
    span: "large",
  },
  {
    id: "10",
    title: "Serene Bedroom",
    description: "A peaceful bedroom retreat inspired by Pokhara's lakeside tranquility, featuring natural materials and calming colors.",
    category: "featured",
    style: "himalayan-minimalist",
    location: "pokhara",
    type: "image",
    src: "/images/luxury-bedroom.png",
    span: "tall",
  },
  {
    id: "11",
    title: "Contemporary Kitchen",
    description: "A modern kitchen design from Lalitpur that blends functionality with elegant aesthetics, perfect for the contemporary home.",
    category: "featured",
    style: "newari-heritage",
    location: "lalitpur",
    type: "image",
    src: "/images/luxury-kitchen.png",
    span: "wide",
  },
]